### ISSUE TITLE
would it work to enumerate all global using in one file and make them part of nuget? 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [losttech/TypeNum#2]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/globalusingdirective

**Comment by dzmitry-lahoda** [comment]
yes, can do it https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#using

**Comment by lostmsu** [comment]
@dzmitry-lahoda what is the relevance of this issue to the project?

**Comment by dzmitry-lahoda** [comment]
ok, may be it will be clear next time:) but I see huge relevance.

**Comment by lostmsu** [comment]
Do you mean to clean up the code a bit with C# 10 features? There's not much point opening an issue for this, just reformat it and send a PR.

I'd probably also switched all files to namespace-scope.

**Comment by dzmitry-lahoda** [comment]
i can be updated to the readme to show how global using can improve things when having multi-file projects. and maybe if that is possible can add file via using in project to make shortcut to typenum even more build int.
